from . import hr_department
from . import hospital_staff
from . import hospital_specialization
from . import hospital_clinic
from . import hospital_doctor
from . import hospital_nurse
from . import hospital_manager
from . import hospital_receptionist
from . import hospital_patient
from . import hospital_disease
from . import hospital_lab_test
from . import hospital_radiology_service
from . import hospital_appointment
from . import hospital_vital_signs
from . import hospital_diagnosis
from . import hospital_prescription
from . import hospital_prescription_line
from . import hospital_lab_order
from . import hospital_lab_order_line
from . import hospital_lab_test_result
from . import hospital_radiology_order
from . import hospital_radiology_result
from . import hospital_medicine
